FROM debian:stable-slim@sha256:04634311a8d5fc442b6eb06d792293c4f3e2268652ca7634e00ce8ef5cc0a28a AS builder

EXPOSE 9978

# Install build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       git \
       golang-go \
       ca-certificates

# Clone and build gpsd-exporter
RUN git clone https://github.com/natesales/gpsd-exporter.git /src \
    && cd /src \
    && go build -o gpsd-exporter .

FROM debian:stable-slim@sha256:04634311a8d5fc442b6eb06d792293c4f3e2268652ca7634e00ce8ef5cc0a28a

# Copy the built binary
COPY --from=builder /src/gpsd-exporter /usr/bin/gpsd-exporter

ENTRYPOINT ["/usr/bin/gpsd-exporter", "-d", "gpsd:2947"]

