FROM debian:stable-slim@sha256:85dfcffff3c1e193877f143d05eaba8ae7f3f95cb0a32e0bc04a448077e1ac69 AS builder

EXPOSE 9978

# Install build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       git \
       golang-go \
       ca-certificates

# Clone and build gpsd-exporter
RUN git clone https://github.com/natesales/gpsd-exporter.git /src \
    && cd /src \
    && go build -o gpsd-exporter .

FROM debian:stable-slim@sha256:85dfcffff3c1e193877f143d05eaba8ae7f3f95cb0a32e0bc04a448077e1ac69

# Copy the built binary
COPY --from=builder /src/gpsd-exporter /usr/bin/gpsd-exporter

ENTRYPOINT ["/usr/bin/gpsd-exporter", "-d", "gpsd:2947"]

