FROM debian:stable-slim@sha256:8f0c555de6a2f9c2bda1b170b67479d11f7f5e3b66bb4a7a1d8843361c9dd3ff

RUN apt-get update && apt-get install -y --no-install-recommends \
    gpsd \
    gpsd-clients \
    pps-tools \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Create directory for socket
# RUN mkdir -p /var/run/gpsd && \
#     chown -R root:root /var/run/gpsd

# Expose GPSD port
EXPOSE 2947

HEALTHCHECK --start-period=1s --interval=30s --timeout=10s --retries=3 CMD gpspipe -r -n 1 || exit 1

COPY --chmod=755 ./gpsd/entrypoint.sh /entrypoint.sh

# Run GPSD in foreground, listening on all interfaces
# -N: don't daemonize
# -n: don't wait for client to connect before polling
# -G: listen on all addresses (not just localhost)
ENTRYPOINT ["/entrypoint.sh"]
