FROM debian:stable-slim@sha256:85dfcffff3c1e193877f143d05eaba8ae7f3f95cb0a32e0bc04a448077e1ac69

RUN apt-get update && apt-get install -y --no-install-recommends \
    chrony \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Create chrony user
RUN groupadd -r chrony && useradd -r -g chrony chrony

# Create directory for sockets
RUN mkdir -p /var/run/chrony && \
    chown -R chrony:chrony /var/run/chrony

# Create directory for chrony data and set ownership
RUN mkdir -p /var/lib/chrony && \
    chown -R chrony:chrony /var/lib/chrony

# Set ownership of chrony configuration directory
RUN mkdir -p /etc/chrony && \
    chown -R chrony:chrony /etc/chrony

# Expose NTP port
EXPOSE 123/udp

# expose the chrony control port
EXPOSE 323/udp

# Tell Docker how to monitor the status of the container
HEALTHCHECK --start-period=1s --interval=30s --timeout=10s --retries=3 CMD chronyc -n tracking || exit 1

COPY --chmod=755 ./chrony/entrypoint.sh /entrypoint.sh

# Switch to chrony user
#USER chrony

# Run the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]
